# 张量

In [2]:
import torch

# 不同维度的张量演示。
# 标量（0维）。
scaler = torch.tensor(3.0)
# 向量（1维）。
vector = torch.tensor([1, 2, 3])
# 矩阵（2维）。
matrix = torch.tensor([[1, 2], [3, 4]])
# RGB图像（3维）。
image = torch.rand(3, 224, 224)
# 视频片段（4维）。
video = torch.rand(10, 3, 224, 224)

print(scaler)
print(vector)
print("标量形状：", scaler.shape)
print("图像形状：", image.shape, image.size())
print("某个维度的长度：",  image.shape[0], image.size(0))



tensor(3.)
tensor([1, 2, 3])
标量形状： torch.Size([])
图像形状： torch.Size([3, 224, 224]) torch.Size([3, 224, 224])
某个维度的长度： 3 3


# 创建张量

In [3]:
import numpy as np

# 从Python列表创建。
t1 = torch.tensor([1, 2, 3])
# 从ndarray数组创建张量，共享底层内存。
array = np.array([4, 5, 6])
t2 = torch.from_numpy(array)
array[0] = 100
print(array)
print(t2)
# 通过tensor创建张量，不共享底层内存（数据复制）。
array = np.array([4, 5, 6])
t3 = torch.tensor(array)
array[0] = 100
print(array)
print(t3)

# PyTorch很多操作与Numpy都很相似。
print(torch.zeros(size=(2, 3)))
print(torch.ones(size=(2, 3)))
print(torch.arange(0, 10, 2))
print(torch.linspace(0, 1, 5))

print(torch.rand(2, 3))
print(torch.randn(2, 3))
print(torch.randint(0, 10, (2, 3)))

[100   5   6]
tensor([100,   5,   6], dtype=torch.int32)
[100   5   6]
tensor([4, 5, 6], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[0.9355, 0.2964, 0.5275],
        [0.9504, 0.8407, 0.7923]])
tensor([[ 0.9628,  1.3742, -0.3206],
        [-0.6221,  0.1461, -2.4425]])
tensor([[0, 4, 5],
        [1, 3, 3]])


# 数据类型与设备

In [4]:
# 指定数据类型。
t1 = torch.tensor([2], dtype=torch.int16)
t2 = torch.tensor([2], dtype=torch.float32)
print(t1, t2)

# 指定设备，优先创建在GPU上，如果没有cuda环境，则创建在CPU上。
device = "cuda" if torch.cuda.is_available() else "cpu"
# 在指定的设备上创建张量。如果没有显式指定，则张量创建在CPU上。
t3 = torch.tensor([1], device=device)
# 张量所属的设备。
print(t1.device, t2.device, t3.device)


# 不同设备的张量，不能进行运算。
# print(t1 + t3)
# 张量的复制。在CPU与GPU之间复制。
t1 = t1.to("cuda")
print(t1.device)
print(t1 + t3)

tensor([2], dtype=torch.int16) tensor([2.])
cpu cpu cuda:0
cuda:0
tensor([3], device='cuda:0')


# 张量的属性

In [5]:
t = torch.rand(2, 3, dtype=torch.float32)
print("形状：", t.shape)
print("数据类型：", t.dtype)
print("设备：", t.device)
print("维度数：", t.ndim)
print("元素的数量：", t.numel())
print("是否在GPU上：", t.is_cuda)
print("是否计算梯度：", t.requires_grad)

形状： torch.Size([2, 3])
数据类型： torch.float32
设备： cpu
维度数： 2
元素的数量： 6
是否在GPU上： False
是否计算梯度： False


# 张量操作

In [6]:
t = torch.tensor([[1, 2], [3, 4]])
# 支持索引与切片。
print(t[0, 1])
print(t[:, 0:1])
# 对维度重新排列，返回原始张量的视图。
print(t.permute(1, 0))
# 张量的转置。
print(t.T, t.t())
# 内存是否连续。
t_trans = t.T
print("内存是否连续：", t.is_contiguous(), t_trans.is_contiguous())

# 改变张量的形状。
# view总是尝试返回视图，不复制数据，要求张量在内存中必须是连续的。
# reshape优先返回视图（共享底层数据），如果无法做到（数据不连续），则返回拷贝。
print(t.view(-1))
# 错误，张量在内存中并不连续。
# print(t_trans.view(-1))
print(t_trans.reshape(-1))
print(t_trans.contiguous().view(-1))

# 在指定的位置插入一个新维度，长度为1。
t = torch.tensor([1, 2, 3])
print('*'*30)
print(t.unsqueeze(0).shape)
print(t.unsqueeze(1).shape)
# 删除指定位置长度为1的维度。如果没有指定，则删除所有长度为1的维度。
t = torch.rand(1, 5, 2, 1)
print(t.shape)
print(t.squeeze(0).shape, t.squeeze(3).shape, t.squeeze().shape)

tensor(2)
tensor([[1],
        [3]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]]) tensor([[1, 3],
        [2, 4]])
内存是否连续： True False
tensor([1, 2, 3, 4])
tensor([1, 3, 2, 4])
tensor([1, 3, 2, 4])
******************************
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([1, 5, 2, 1])
torch.Size([5, 2, 1]) torch.Size([1, 5, 2]) torch.Size([5, 2])


# 数学运算与广播

In [11]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)
# 张量与标量广播。
print(a + 1)
# 不同形状张量广播。
matrix = torch.ones(2, 3)
vector = torch.tensor([1, 2, 3])
print('2*3:1',matrix + vector)

mat_a = torch.rand(2, 3)
mat_b = torch.rand(3, 2)
# 矩阵乘法。
mat_mult = torch.mm(mat_a, mat_b)
mat_mult2 = mat_a @ mat_b
print('mm:',mat_mult.shape, '@:',mat_mult2.shape)

# 聚合运算。
print(torch.sum(a))
print(torch.mean(a.float()))
print(torch.max(a))

tensor([5, 7, 9])
tensor([2, 3, 4])
2*3:1 tensor([[2., 3., 4.],
        [2., 3., 4.]])
mm: torch.Size([2, 2]) @: torch.Size([2, 2])
tensor(6)
tensor(2.)
tensor(3)


# 与Numpy互操作

In [8]:
# tensor -> Numpy
t = torch.tensor([1., 2., 3.])
# 张量转换为ndarray数组，共享内存。
arr = t.numpy()
t[0] = 100
print(arr)

# Numpy -> tensor
arr = np.array([4, 5, 6])
# ndarray数组创建张量。共享内存。
t = torch.from_numpy(arr)
arr[0] = 100
print(t)

# 不共享内存。
arr = np.array([4, 5, 6])
t = torch.tensor(arr)
arr[0] = 100
print(t)

t = torch.tensor([1., 2., 3.])
arr = np.array(t)
t[0] = 100
print(arr)

t = torch.tensor(5.0)
print(type(t.numpy()), t.numpy())
# 获取张量的标量值，返回标量类型，而不返回数组类型。
v = t.item()
print(type(v), v)

[100.   2.   3.]
tensor([100,   5,   6], dtype=torch.int32)
tensor([4, 5, 6], dtype=torch.int32)
[1. 2. 3.]
<class 'numpy.ndarray'> 5.0
<class 'float'> 5.0
