In [12]:
import numpy as np
#my draft
class MyStandardScaler:
    def __init__(self):
        self.mean_=None
        self.scale_=None

    def fit(self,X):
        X=np.asarray(X)
        self.mean_=X.mean(axis=0)
        self.std_=X.std(axis=0)
        return self
    def transform(self,X):
        if self.mean_ is None or self.std_ is None:
            raise RuntimeError("先调用fit")
        return (X-self.mean_)/self.std_
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self,X_scaled):
        if self.mean_ is None or self.std_ is None:
            raise RuntimeError("先调用fit")
        return X_scaled*self.std_+self.mean_

In [14]:
# 随机生成shape=(5, 2)、取值50-100的数组
np.random.seed(2)  # 固定随机种子，保证结果可复现
X = np.random.randint(50, 101, size=(5, 2)).astype(float)  # 转为float避免整数运算误差
print("原始数据：")
print(X)

# 初始化标准化类并执行转换与还原
scaler = MyStandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = scaler.inverse_transform(X_scaled)

print("\n标准化后的数据：")
print(X_scaled)
print("\n还原后的数据（应与原始数据一致）：")
print(X_original)

原始数据：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]

标准化后的数据：
[[ 0.64549722 -0.13440323]
 [ 1.10656667 -0.65708246]
 [-1.01435278  1.95631369]
 [-1.38320834 -0.43307708]
 [ 0.64549722 -0.73175092]]

还原后的数据（应与原始数据一致）：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]


In [15]:
#ai optimized  definitive version
import numpy as np
class StandardScaler:
    def __init__(self):
        # 存储每个特征的均值和标准差
        self.mean_ = None
        self.scale_ = None

    def fit(self, X):
        """通过训练数据学习转换规则（计算每个特征的均值和标准差）"""
        # X的形状为(样本数, 特征数)
        self.mean_ = np.mean(X, axis=0)  # 按列计算均值
        self.scale_ = np.std(X, axis=0)  # 按列计算标准差
        return self

    def transform(self, X):
        """使用fit学习的规则转换数据"""
        # 标准化公式：(X - 均值) / 标准差
        return (X - self.mean_) / self.scale_

    def fit_transform(self, X):
        """先fit再transform的合并方法"""
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self, X_scaled):
        """将标准化后的数据还原为原始数据"""
        return X_scaled * self.scale_ + self.mean_

In [6]:
# 随机生成shape=(5, 2)、取值50-100的数组
np.random.seed(2)  # 固定随机种子，保证结果可复现
X = np.random.randint(50, 101, size=(5, 2)).astype(float)  # 转为float避免整数运算误差
print("原始数据：")
print(X)

# 初始化标准化类并执行转换与还原
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = scaler.inverse_transform(X_scaled)

print("\n标准化后的数据：")
print(X_scaled)
print("\n还原后的数据（应与原始数据一致）：")
print(X_original)

原始数据：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]

标准化后的数据：
[[ 0.64549722 -0.13440323]
 [ 1.10656667 -0.65708246]
 [-1.01435278  1.95631369]
 [-1.38320834 -0.43307708]
 [ 0.64549722 -0.73175092]]

还原后的数据（应与原始数据一致）：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]


In [1]:
#teacher draft
import numpy as np

class MyStandardScaler:
    def fit(self, X):
        """
        Parameters
        ----------
        X : array-like, shape=(n_samples, n_features)
            训练数据。
        """
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)
        return self
    
    def transform(self, X):
        return (X - self.mean_) / self.std_
    
    def fit_transform(self, X):
        return self.fit(X).transform(X)
    
    def inverse_transform(self, X):
        return X * self.std_ + self.mean_
    

np.random.seed(0)
X = np.random.uniform(5, 10, size=(5, 2))
print(X)
ss = MyStandardScaler()
X_trans = ss.fit_transform(X)
print(X_trans)
X_restore = ss.inverse_transform(X_trans)
print(X_restore)

[[7.74406752 8.57594683]
 [8.01381688 7.72441591]
 [7.118274   8.22947057]
 [7.18793606 9.458865  ]
 [9.8183138  6.91720759]]
[[-0.23705658  0.46543548]
 [ 0.038081   -0.53853409]
 [-0.87535026  0.05693401]
 [-0.80429671  1.50641116]
 [ 1.87862256 -1.49024656]]
[[7.74406752 8.57594683]
 [8.01381688 7.72441591]
 [7.118274   8.22947057]
 [7.18793606 9.458865  ]
 [9.8183138  6.91720759]]


In [2]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
X_trans=mm.fit_transform(X)
print(X_trans)
X_restore=mm.inverse_transform(X_trans)
print(X_restore)

[[0.23177196 0.65262109]
 [0.33167766 0.31759132]
 [0.         0.51630207]
 [0.02580038 1.        ]
 [1.         0.        ]]
[[7.74406752 8.57594683]
 [8.01381688 7.72441591]
 [7.118274   8.22947057]
 [7.18793606 9.458865  ]
 [9.8183138  6.91720759]]


In [3]:
import numpy as np

class MyMinMaxScaler:
    def __init__(self, feature_range=(0, 1)):
        self.feature_range = feature_range
        self.data_min_ = None
        self.data_max_ = None
        self.data_range_ = None
        self.scale_ = None
        self.min_ = None

    def fit(self, X):
        """
        学习缩放规则（每个特征的 min / max）
        """
        X = np.asarray(X)

        # 每一列的最小值 / 最大值
        self.data_min_ = X.min(axis=0)
        self.data_max_ = X.max(axis=0)
        self.data_range_ = self.data_max_ - self.data_min_

        # 防止除 0（与 sklearn 思路一致）
        self.data_range_[self.data_range_ == 0] = 1.0

        # 映射到 feature_range
        fr_min, fr_max = self.feature_range
        self.scale_ = (fr_max - fr_min) / self.data_range_
        self.min_ = fr_min - self.data_min_ * self.scale_

        return self

    def transform(self, X):
        """
        按 fit 学到的规则进行缩放
        """
        if self.data_min_ is None:
            raise RuntimeError("MyMinMaxScaler has not been fitted yet.")

        X = np.asarray(X)
        X_scaled = X * self.scale_ + self.min_
        return X_scaled

    def fit_transform(self, X):
        """
        fit + transform
        """
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self, X_scaled):
        """
        将缩放后的数据还原
        """
        if self.data_min_ is None:
            raise RuntimeError("MyMinMaxScaler has not been fitted yet.")

        X_scaled = np.asarray(X_scaled)
        fr_min, fr_max = self.feature_range

        X = (X_scaled - self.min_) / self.scale_
        return X


In [4]:
from sklearn.preprocessing import MinMaxScaler

X = np.array([[1, 2],
              [2, 4],
              [3, 6]])

sk = MinMaxScaler()
my = MyMinMaxScaler()

print(sk.fit_transform(X))
print(my.fit_transform(X))

print(sk.inverse_transform(sk.transform(X)))
print(my.inverse_transform(my.transform(X)))


[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
[[1. 2.]
 [2. 4.]
 [3. 6.]]
[[1. 2.]
 [2. 4.]
 [3. 6.]]
