In [12]:
import numpy as np
#my draft
class MyStandardScaler:
    def __init__(self):
        self.mean_=None
        self.scale_=None

    def fit(self,X):
        X=np.asarray(X)
        self.mean_=X.mean(axis=0)
        self.std_=X.std(axis=0)
        return self
    def transform(self,X):
        if self.mean_ is None or self.std_ is None:
            raise RuntimeError("先调用fit")
        return (X-self.mean_)/self.std_
    def fit_transform(self,X):
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self,X_scaled):
        if self.mean_ is None or self.std_ is None:
            raise RuntimeError("先调用fit")
        return X_scaled*self.std_+self.mean_

In [14]:
# 随机生成shape=(5, 2)、取值50-100的数组
np.random.seed(2)  # 固定随机种子，保证结果可复现
X = np.random.randint(50, 101, size=(5, 2)).astype(float)  # 转为float避免整数运算误差
print("原始数据：")
print(X)

# 初始化标准化类并执行转换与还原
scaler = MyStandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = scaler.inverse_transform(X_scaled)

print("\n标准化后的数据：")
print(X_scaled)
print("\n还原后的数据（应与原始数据一致）：")
print(X_original)

原始数据：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]

标准化后的数据：
[[ 0.64549722 -0.13440323]
 [ 1.10656667 -0.65708246]
 [-1.01435278  1.95631369]
 [-1.38320834 -0.43307708]
 [ 0.64549722 -0.73175092]]

还原后的数据（应与原始数据一致）：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]


In [15]:
#ai optimized  definitive version
import numpy as np
class StandardScaler:
    def __init__(self):
        # 存储每个特征的均值和标准差
        self.mean_ = None
        self.scale_ = None

    def fit(self, X):
        """通过训练数据学习转换规则（计算每个特征的均值和标准差）"""
        # X的形状为(样本数, 特征数)
        self.mean_ = np.mean(X, axis=0)  # 按列计算均值
        self.scale_ = np.std(X, axis=0)  # 按列计算标准差
        return self

    def transform(self, X):
        """使用fit学习的规则转换数据"""
        # 标准化公式：(X - 均值) / 标准差
        return (X - self.mean_) / self.scale_

    def fit_transform(self, X):
        """先fit再transform的合并方法"""
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self, X_scaled):
        """将标准化后的数据还原为原始数据"""
        return X_scaled * self.scale_ + self.mean_

In [6]:
# 随机生成shape=(5, 2)、取值50-100的数组
np.random.seed(2)  # 固定随机种子，保证结果可复现
X = np.random.randint(50, 101, size=(5, 2)).astype(float)  # 转为float避免整数运算误差
print("原始数据：")
print(X)

# 初始化标准化类并执行转换与还原
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_original = scaler.inverse_transform(X_scaled)

print("\n标准化后的数据：")
print(X_scaled)
print("\n还原后的数据（应与原始数据一致）：")
print(X_original)

原始数据：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]

标准化后的数据：
[[ 0.64549722 -0.13440323]
 [ 1.10656667 -0.65708246]
 [-1.01435278  1.95631369]
 [-1.38320834 -0.43307708]
 [ 0.64549722 -0.73175092]]

还原后的数据（应与原始数据一致）：
[[90. 65.]
 [95. 58.]
 [72. 93.]
 [68. 61.]
 [90. 57.]]
