In [49]:
import numpy as np
#my draft
def my_make_regression(n_samples,n_features,bias=0,coef=False,noise=0,random_state=None):
    np.random.seed(random_state)
    X=np.random.randn(n_samples,n_features)
    w=np.random.randn(n_features)*100
    y=X@w+bias
    if noise>0:
        y= y+np.random.randn(n_samples)*noise
    if coef is True:
        return X,y,w
    else:
        return X,y


In [63]:
x,y,w=my_make_regression(n_samples=10,n_features=3,bias=20,noise=5,coef=True,random_state=1)
x,y,w

(array([[ 1.62434536, -0.61175641, -0.52817175],
        [-1.07296862,  0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ,  0.3190391 ],
        [-0.24937038,  1.46210794, -2.06014071],
        [-0.3224172 , -0.38405435,  1.13376944],
        [-1.09989127, -0.17242821, -0.87785842],
        [ 0.04221375,  0.58281521, -1.10061918],
        [ 1.14472371,  0.90159072,  0.50249434],
        [ 0.90085595, -0.68372786, -0.12289023],
        [-0.93576943, -0.26788808,  0.53035547]]),
 array([ -36.00944935,  214.67690089,  -92.46744809,  115.21901572,
         -19.19963787,  171.53935685,   73.29860765, -130.43619291,
         -11.17499036,   55.17168179]),
 array([-69.16607517, -39.67535269, -68.71727001]))

In [62]:
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=10,n_features=3,bias=20,noise=5,random_state=1)
x,y

(array([[ 0.58281521,  0.04221375, -1.10061918],
        [-0.7612069 ,  1.74481176,  0.3190391 ],
        [-0.26788808, -0.93576943,  0.53035547],
        [-0.38405435, -0.3224172 ,  1.13376944],
        [-0.61175641,  1.62434536, -0.52817175],
        [ 1.46210794, -0.24937038, -2.06014071],
        [-0.17242821, -1.09989127, -0.87785842],
        [-0.68372786,  0.90085595, -0.12289023],
        [ 0.86540763, -1.07296862, -2.3015387 ],
        [ 0.90159072,  1.14472371,  0.50249434]]),
 array([ 28.04009623,  60.61893869,  -7.85324793,   8.43940554,
         52.47588159,  19.152179  , -18.70269649,  33.74606961,
         -0.80057892,  60.18538496]))

In [ ]:
#ai optimized definitive version
def my_make_regression(n_samples, n_features, noise=0.0, coef=False):
    import numpy as np
    
    # 参数检查，用 assert
    assert isinstance(n_samples, int) and n_samples > 0, "n_samples 必须为正整数"
    assert isinstance(n_features, int) and n_features > 0, "n_features 必须为正整数"
    assert isinstance(noise, (int, float)) and noise >= 0, "noise 必须为非负数"
    assert isinstance(coef, bool), "coef 必须是布尔值 True 或 False"
    
    X = np.random.randn(n_samples, n_features)
    w = np.random.randn(n_features)
    y = X @ w
    
    if noise > 0:
        y += np.random.randn(n_samples) * noise
    
    return (X, y, w) if coef else (X, y)


In [64]:
from sklearn.datasets import make_regression
import inspect

print(inspect.getsource(make_regression))


@validate_params(
    {
        "n_samples": [Interval(Integral, 1, None, closed="left")],
        "n_features": [Interval(Integral, 1, None, closed="left")],
        "n_informative": [Interval(Integral, 0, None, closed="left")],
        "n_targets": [Interval(Integral, 1, None, closed="left")],
        "bias": [Interval(Real, None, None, closed="neither")],
        "effective_rank": [Interval(Integral, 1, None, closed="left"), None],
        "tail_strength": [Interval(Real, 0, 1, closed="both")],
        "noise": [Interval(Real, 0, None, closed="left")],
        "shuffle": ["boolean"],
        "coef": ["boolean"],
        "random_state": ["random_state"],
    },
    prefer_skip_nested_validation=True,
)
def make_regression(
    n_samples=100,
    n_features=100,
    *,
    n_informative=10,
    n_targets=1,
    bias=0.0,
    effective_rank=None,
    tail_strength=0.5,
    noise=0.0,
    shuffle=True,
    coef=False,
    random_state=None,
):
    """Generate a random regression problem