In [10]:
#矩阵点积运算规则
import numpy as np
a=np.array([[1,2,3],[4,5,6]])#2行3列
b=np.array([[1,2],[3,4],[5,6]])#3行2列
c=np.dot(a,b)
print(a)
print(a.shape)
print(b)
print(c)#若不满足m×n与n×k的形状，会报错

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [3]:
#矩阵的转置
#第i行=》第i列
print(a.T)
#一维时，情况有变化
d=np.array([1,2,3])
print(d)
print(d.T)#一维时，不存在行向量变列向量，即转置不会改变维度数

[[1 4]
 [2 5]
 [3 6]]
[1 2 3]
[1 2 3]


In [ ]:
#dot运算
#1 当两个参数都是一维数组时，执行向量的点积运算
a=[1,2,3]
b=[4,5,6]
np.dot(a,b)
#也可以使用@来运算
a=np.asarray(a)
b=np.asarray(b)
print(a@b)#@运算不支持list，需要转换为ndarray数组

#2 当两个参数都是2维数组时，执行矩阵的点积运算
a=np.array([[1,2],[3,4]])
b=np.array([[0,2],[1,5]])
print(a@b)

#3 当左侧是高维数组，右侧是一维数组时，使用左侧数组的最内层与右侧数组进行点积运算
a=np.array([[1,2],[3,4]])
b=np.array([0,2])
print(a@b)
c=np.arange(24).reshape(3,4,2)#shape的顺序为axis=0,1,2……
print(c)
print(c@b)

32

32
[[ 2 12]
 [ 4 26]]
[4 8]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 2  6 10 14]
 [18 22 26 30]
 [34 38 42 46]]
