In [8]:
#矩阵点积运算规则
import numpy as np
a=np.array([[1,2,3],[4,5,6]])#2行3列
b=np.array([[1,2],[3,4],[5,6]])#3行2列
c=np.dot(a,b)
print(a)
print(b)
print(c)#若不满足m×n与n×k的形状，会报错

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [ ]:
#矩阵的转置
#第i行=》第i列
print(a.T)
#一维时，情况有变化
d=np.array([1,2,3])
print(d)
print(d.T)#一维时，不存在行向量变列向量，即转置不会改变维度数


[[1 4]
 [2 5]
 [3 6]]
[1 2 3]
[1 2 3]
