In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
c=np.dot(a,b)
c
d=np.array([1,2,3])
e=np.dot(a,d)
e
f=np.arange(48).reshape(2,4,2,3)
f
g=np.dot(f,d)
g

array([[22, 28],
       [49, 64]])

array([14, 32])

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]]]])

array([[[  8,  26],
        [ 44,  62],
        [ 80,  98],
        [116, 134]],

       [[152, 170],
        [188, 206],
        [224, 242],
        [260, 278]]])