In [ ]:
import numpy as np
def my_train_test_split(x,y,test_size=0.3,shuffle=True,random_state=None):
        x=np.asarray(x)
        y=np.asarray(y)#确保xy是ndarray数组
        np.random.seed(random_state)
        if shuffle:
                index=np.arange(len(x))
                np.random.shuffle(index)
                x=x[index]
                y=y[index]
        if type(test_size)==float:
                test_size=round(len(x)*test_size)#round()：对浮点数进行四舍五入
        return x[:-test_size],x[-test_size:],y[:-test_size],y[-test_size:]
#生成测试数据
x=np.arange(10)
y=np.arange(20,30)
x_train,x_test,y_train,y_test=my_train_test_split(x,y,test_size=0.3,shuffle=True,random_state=323)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[1 7 5 2 3 9 4]
[0 6 8]
[21 27 25 22 23 29 24]
[20 26 28]
